apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-factorial-app
  namespace: factorial
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: factorial-app
  template:
    metadata:
      labels:
        app: factorial-app
    spec:
      terminationGracePeriodSeconds: 60 #굳이 설정 안해도되는데 테스트겸 설정해보기 default 30 초
      containers:
        - name: factorial
          image: 0892668/factorial-app:0.0.3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 10"]
          startupProbe:
            httpGet:
              path: /probe/startup
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 1
            failureThreshold: 10 #약간 높게 잡기
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 1
            successThreshold: 2
            failureThreshold: 3 #민감하게 잡기
          livenessProbe:
            httpGet:
              path: /probe/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 1
            failureThreshold: 7 # 조금 더 둔감하게 설정

