apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: factorial-hpa
  namespace: factorial
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: my-factorial-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 30