spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  data:
    redis:
      host: redis-service.default.svc.cluster.local
      port: 6379
